### ISSUE TITLE
Can't create room. 

### ISSUE THREAD

**Issue by Neko-22** [meanwhile-at-the-lab/partywat.ch#3]
Just tried to run a test with the current inital-websockets branch. Creating a room seems to be broken. Svelte is giving this error:
```
SvelteKitError: Not found: /undefined/api/create-room
    at resolve (/home/cormac/partywat.ch/frontend/node_modules/@sveltejs/kit/src/runtime/server/respond.js:530:13)
    at resolve (/home/cormac/partywat.ch/frontend/node_modules/@sveltejs/kit/src/runtime/server/respond.js:330:5)
    at Object.eval [as handle] (/home/cormac/partywat.ch/frontend/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
    at Module.respond (/home/cormac/partywat.ch/frontend/node_modules/@sveltejs/kit/src/runtime/server/respond.js:327:40) {
  status: 404,
  text: 'Not Found'
}
```
Seems to be a backend issue.

**Comment by Captainexpo-1** [comment]
Did you create both .env files in the frontend and backend?

**Comment by Neko-22** [comment]
hm. that'll do it.

**Comment by Neko-22** [comment]
yeah still doesnt work even after renaming the .example files to .env. i cant debug further atm, apologies

**Comment by Captainexpo-1** [comment]
hmm

**Comment by Captainexpo-1** [comment]
Oh. I forgot to add VITE_API_URL=http://localhost:8000 to the .env.example in the frontend 🤦

**Comment by Neko-22** [comment]
that'll do it! i'll check that when i get back home
